name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4

      - name: setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test

      - name: typecheck
        run: pnpm typecheck
